name: Bug report
description: Report an issue with the server installer
title: '[Bug]: '
labels:
  - 'Bug'
body:
  - type: textarea
    id: logfiles
    attributes:
      label: Log Files
      description: Drag and drop the ftb-server-installer.log file here or link to a gist/hastebin/pastebin/ect
      placeholder: >-
        Either drag and drop the log file here or upload it to a pastebin site
        and paste a link here
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue you are having
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps on how we can reproduce the issue
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Add any other information that you think may be helpful here
